version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraper
      POSTGRES_DB: scraper
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-postgres:
